spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      #hibernate tarafındaki validation engelle
    properties:
       javax:
        persistence:
          validation:
            mode: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: 12345
    driverClassName: org.postgresql.Driver
server:
  port: 8081



